title: TypeScript Native Compiler (AOT)
email: duzhar@googlemail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
domain: asdalexander77.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
baseurl: ""   	                       # the subpath of your site, e.g. /blog
url: https://asdalexander77.github.io/ # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: _Alex__D_
github_username:  ASDAlexander77

# Build settings
theme: minima
#theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-theme-minimal
  - jekyll-relative-links

header_pages:
  - about.markdown
  - portfolio.markdown

relative_links:
  enabled:     true
  collections: false